language: go

go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x

env:
  global:
    - BUILD_GOARCH=amd64
    - GO111MODULE=on
  matrix:
    - BUILD_GOOS=linux
    - BUILD_GOOS=darwin

# install:
# - if [[ $TRAVIS_GO_VERSION == 1.11.* ]]; then go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0; fi
# - if [[ $TRAVIS_GO_VERSION != 1.11.* ]]; then go get github.com/golangci/golangci-lint/cmd/golangci-lint; fi

before_script:
  - go version
  - go env

script:
  - go vet ./...
  - go test -v --cover ./...
